name: CI

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [develop]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: corepack enable
      - run: pnpm install

      - name: Lint
        run: pnpm run lint

      - name: Type Check
        run: pnpm run type-check

      - name: Jest Test
        run: pnpm run test -- --passWithNoTests

      - name: Prisma Validate
        run: npx prisma validate
        env:
          DATABASE_URL: postgresql://user:password@localhost:5432/dbname
          DIRECT_URL: postgresql://user:password@localhost:5432/dbname

      - name: Prisma Generate
        run: npx prisma generate

      - name: Build
        run: pnpm run build
